### ISSUE TITLE
Is YML also allowed?

### ISSUE THREAD

**Issue by visualcookie** [DavidePastore/Slim-Config#7]
Hi,

just a question. In the README.md you set the things up with a `config.json`. Can this also be a YML file or has it to be a JSON? If so, would it be easy to add YML as supported config file.

**Comment by DavidePastore** [comment]
Hi @visualcookie, yes YML files are supported too. For example you can do:

``` php
// Register provider
$container['config'] = function () {
  //Create the configuration
  return new \DavidePastore\Slim\Config\Config('config.yml');
};

// Register middleware for all routes
// If you are implementing per-route checks you must not add this
$app->add($container->get('config'));

$app->get('/foo', function ($req, $res, $args) {
  //Here you have your configuration
  $config = $this->config->getConfig();
  $secret = $config->get('application.secret');
});
```

Your YML file could be:

``` yml
application:
    name: configuration
    secret: s3cr3t
host: localhost
port: 80
servers:
- host1
- host2
- host3
```
